version: '3.6'
services:
  app:
    image: openjdk:15
    ports:
      - 8080:8080
    tty: true
    volumes:
      - ./server:/srv:cached
    working_dir: /srv
  node:
    build: ./node
    ports:
      - "4200:4200"
    volumes:
      - "./server:/projects"
    tty: true